# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "capty-app"
client_id = ""
application_url = "https://localhost:3000"
embedded = true

[access_scopes]
scopes = "read_products,read_orders,write_products"

[auth]
redirect_urls = []  # Managed automatically by Shopify CLI

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
